title: Christy Ehlert-Mackie # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data Analyst who ðŸ’— Excel | SQL | Tableau | I analyze and interpret data so companies have the information and insights they need to make sound business decisions.  <br><br>
  <a href="https://www.linkedin.com/in/averyjsmith/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
